### ISSUE TITLE
Better compilation error message

### ISSUE THREAD

**Issue by imranismail** [slime-lang/slime#150]
Currently the error message doesn't include the path to the template that it's compiling.

It's just showing the View's function body. Is there a way to identify which template it is failing at?

```
== Compilation error in file lib/fave/views/reservation_view.ex ==
** (Slime.TemplateSyntaxError) got ArgumentError with message "argument error" while retrieving Exception.message/1 for %Slime.TemplateSyntaxError{column: 0, line: "  .ui.container", line_number: 9, message: "{:no_match, <<14>>}", source: "INPUT"}
    lib/slime/parser.ex:14: Slime.Parser.parse/1
    lib/slime/renderer.ex:17: Slime.Renderer.precompile/1
    lib/phoenix_slime/engine.ex:9: PhoenixSlime.Engine.compile/2
    (phoenix) lib/phoenix/template.ex:378: Phoenix.Template.compile/2
    (phoenix) lib/phoenix/template.ex:186: anonymous fn/3 in Phoenix.Template."MACRO-__before_compile__"/2
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix) expanding macro: Phoenix.Template.__before_compile__/1
    lib/fave/views/reservation_view.ex:1: Fave.ReservationView (module)
    (elixir) lib/kernel/parallel_compiler.ex:206: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

**Comment by Rakoth** [comment]
Thanks for the report.
It would be great to pass template file name along with error message, do you want to look into this?

**Comment by Rakoth** [comment]
@imranismail You can try installing slime from master branch, this argument error is now fixed and indentation errors have better message

**Comment by szsoppa** [comment]
Hi! I'm using the latest master version of Slime, and it seems like there is still a problem with the proper error compilation message.

Just in case, I have the proper config set:
```elixir
config :slime, :keep_lines, true
```

Libs versions:
- elixir `1.11.0-rc.0`
- phoenix `1.5.5`
- phoenix_slime `0.13.1`
